### PR TITLE
chore: Update API to 3.19.0

### PR DESCRIPTION
**Pull request by lemaitre-aneo**
https://github.com/aneoconsulting/ArmoniK.Api/releases/tag/3.19.0

### CODE REVIEW

**Review by ngruelaneo — APPROVED** [review]

**Review by aneojgurhem — APPROVED** [review]
payload id is also missing in some return type in grpc task service

**Comment by lemaitre-aneo** [comment]
> payload id is also missing in some return type in grpc task service

Where? I think everything is handled in the ToTaskDetailed() method.

**Comment by aneojgurhem** [comment]
> > payload id is also missing in some return type in grpc task service
> 
> Where? I think everything is handled in the ToTaskDetailed() and ToTaskSummary() methods.

Line 480, the return object misses the payload id.

**Review by aneojgurhem — APPROVED** [review]

**Comment by aneojgurhem** [comment]
> I did not change the TaskInfo message, so I was not aware that it exposed payloadId, but never populated.

No problem, this PR reminded me of this issue. Good time to fix a bug !

**Pull request merged**
