### PR TITLE
chore: Update Api version

### PR DESCRIPTION
**Pull request by dbrasseur-aneo**
Adds mTLS support

### CODE REVIEW

**Comment by lemaitre-aneo** [comment]
How is it related to mTLS? I thought it was about the logs?!

**Comment by aneojgurhem** [comment]
> How is it related to mTLS? I thought it was about the logs?!

One part is the update of Api which is related to mtls, the other part is adding missing doc in justfile which should be another pr

**Comment by dbrasseur-aneo** [comment]
> > How is it related to mTLS? I thought it was about the logs?!
> 
> One part is the update of Api which is related to mtls, the other part is adding missing doc in justfile which should be another pr

Should I split it just for a usage doc addition ?

**Comment by aneojgurhem** [comment]
> > > How is it related to mTLS? I thought it was about the logs?!
> > 
> > 
> > One part is the update of Api which is related to mtls, the other part is adding missing doc in justfile which should be another pr
> 
> Should I split it just for a usage doc addition ?

Hell yeah !

**Pull request merged**
